apiVersion: v2
name: postgresql-restic
description: Logical backups of postgresql
type: application
version: 1.0.0
appVersion: v15.2.0-restic-0.15.1
icon: https://avatars.githubusercontent.com/u/10073512
