{{- range .Values.networkPolicy.egress.namespaces }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "app-manifests.name" $ }}-{{ .name }}-egress-namespaces
  labels:
    {{- include "app-manifests.labels" $ | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- toYaml (default dict .matchLabels) | nindent 6 }}
  egress:
    {{- range .namespaces }}
    - toEndpoints:
      - matchLabels:
          k8s:io.kubernetes.pod.namespace: {{ . }}
    {{- end }}
---
{{- end }}
