{{- range .Values.originCertificates }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "contour-manifests.certificate-name" .certificateName }}
  labels:
    {{- include "contour-manifests.labels" $ | nindent 4 }}
type: kubernetes.io/tls
stringData:
  tls.crt: {{ required "Origin tls.crt is required" .cert }}
  tls.key: {{ required "Origin tls.key is required" .key }}
  ca.crt: {{ .ca | default $.Values.cloudflareOriginCaRsaRoot }}
{{- end }}
