{{- range .Values.originCertificate }}
---
apiVersion: v1
kind: Secret
metadata:
  name: origin-certificate-{{ .certificateName }}
  labels:
    {{- include "contour-manifests.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "Origin tls.crt is required" .cert | b64enc }}
  tls.key: {{ required "Origin tls.key is required" .key | b64enc }}
  ca.crt: {{ required "Cloudflare ca.crt is required" $.Values.cloudflareCertificateAuthority | b64enc }}
{{- end }}
