{{- range .Values.virtualHosts }}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ .name }}
  labels:
    {{- include "contour-manifests.labels" $ | nindent 4 }}
spec:
  virtualhost:
    {{- if .authorization }}
    authorization: {{ .authorization | toYaml | nindent 6 }}
    {{- end }}
    {{- if .corsPolicy }}
    corsPolicy: {{ .corsPolicy | toYaml | nindent 6 }}
    {{- end }}
    fqdn: {{ .fqdn }}
    tls:
      secretName: {{ default (include "contour-manifests.certificate-name" (first $.Values.originCertificates).certificateName) .tlsSecretName }}
      {{- if not (default false .clientValidationDisabled) }}
      clientValidation:
        caSecret: {{ $.Values.cloudflareOriginPullCASecretName }}
      {{- end }}
  includes:
    {{- .includes | toYaml | nindent 4 }}
---
{{- end }}