apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "restic-postgresql.name" . }}-egress
  labels:
    {{- include "restic-postgresql.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  egress:
    - toEndpoints:
      - matchLabels:
          k8s:io.kubernetes.pod.namespace: kube-system
          k8s-app: kube-dns
      toPorts:
      - ports:
        - port: '53'
          protocol: UDP
        rules:
          dns:
            - matchPattern: "*"
    - toEndpoints:
      - matchLabels:
          application: spilo
    - toFQDNs:
        - matchName: {{ include "restic-postgresql.s3Endpoint" . }}
        