apiVersion: v1
kind: Secret
metadata:
  name: {{ include "restic-postgresql.fullname" . }}
  labels:
    {{- include "restic-postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.awsAccessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsSecretAccessKey }}
  RESTIC_PASSWORD: {{ .Values.restic.password }}