httpProxies:
  []
  # - name: "name"
  #   virtualHost:
  #     fqdn: "svc.example.com"
  #   enableWebsockets: false
  #   service:
  #     name: "service-name"
  #     port: 80
  #     protocol: ""

networkPolicy:
  allowIntraNamespace: true
  kubernetesApi: []
  ingress:
    world:
      enabled: no
      matchLabels: {}
      controller:
        namespace: contour
        matchLabels:
          app.kubernetes.io/component: envoy
    allNamespaces: false
    fromNamespaces: []
  egress:
    world: []
    fqdn: []
    # - name: s3-scaleway
    #   matchNames:
    #     - s3.fr-par.scw.cloud
    #   matchLabels:
    #     app: my-app
