httpProxies:
  []
  # - name: "name"
  #   virtualHost:
  #     fqdn: "svc.example.com"
  #   enableWebsockets: false
  #   service:
  #     name: "service-name"
  #     port: 80
  #     protocol: ""

networkPolicy:
  allowIntraNamespace: true
  kubernetesApi: []
  remoteNode: no
  smtp:
    []
    # - name: smtp-app
    #   fqdn: smtp.eu.mailgun.org
    #   matchLabels: {}
  ingress:
    world:
      enabled: no
      matchLabels: {}
      controller:
        namespace: contour
        matchLabels:
          app.kubernetes.io/component: envoy
    allNamespaces: false
    fromNamespaces: []
  egress:
    world: []
    fqdn: []
    namespaces: []
    # - name: s3-scaleway
    #   matchNames:
    #     - s3.fr-par.scw.cloud
    #   matchLabels:
    #     app: my-app
