httpProxies:
  []
  # - name: "name"
  #   enableWebsockets: false
  #   service:
  #     name: "service-name"
  #     port: 80
  #     protocol: ""

networkPolicy:
  allowIntraNamespace: true
  kubernetesApi: []
  ingress:
    fromNamespaces: []
  egress:
    world: []
    fqdn: []
    # - name: s3-scaleway
    #   matchNames:
    #     - s3.fr-par.scw.cloud
    #   matchLabels:
    #     app: my-app
