apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miniflux.fullname" . }}
  labels:
    {{- include "miniflux.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ print "postgres://" .Values.config.postgresqlUsername ":" .Values.postgresql.auth.postgresPassword "@" (include "miniflux.postgresqlHost" .) "/" .Values.postgresql.postgresqlDatabase "?sslmode=disable" }}
  ADMIN_USERNAME: {{ .Values.config.adminUsername }}
  ADMIN_PASSWORD: {{ required "Miniflux admin password is required" .Values.config.adminPassword }}