apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "zalando-cluster.fullname" . }}
  labels:
    {{- include "zalando-cluster.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.zalandoNodeClusterRole }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.podServiceAccount }}
    namespace: {{ .Release.Namespace }}