{{- if .Values.environmentVariables.manageNamespaceConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.environmentVariables.secret }}
  labels:
    {{- include "zalando-cluster.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.s3.key }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secret }}
{{- end }}