apiVersion: v2
name: miniflux
description: Miniflux RSS feed reader chart
type: application
version: 1.0.4
appVersion: 2.1.3
icon: https://cdn-1.webcatalog.io/catalog/miniflux/miniflux-icon-filled-256.png
dependencies:
  - name: postgresql
    version: 15.5.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
